Repository Total-RP/Total-RP-3, pull requests merged in 2020-10, with the labels that each got.

#413 Fixed OOC detection with Russian declension system
  totalRP3/modules/chatframe/chatframe.lua
Labels: bug

#417 Added safeguard for WIM
  totalRP3/modules/chatframe/prat.lua
Labels: bug

#415 Added search bar in own profiles lists ( #35 )
  totalRP3/core/impl/profiles.lua
  totalRP3/core/ui/profiles.xml
  totalRP3/modules/register/companions/register_companions_profiles.lua
  totalRP3/tools/Locale.lua
Labels: enhancement

#416 Default profile ( #122 )
  totalRP3/core/impl/profiles.lua
  totalRP3/core/impl/ui_tools.lua
  totalRP3/modules/register/characters/register_main.lua
  totalRP3/modules/register/characters/register_notes.lua
  totalRP3/modules/register/characters/register_ui_main.xml
  totalRP3/tools/Locale.lua
Labels: enhancement

#425 Sanitizing % character in popups
  totalRP3/core/impl/popup.lua
Labels: bug

#430 Fix profile backgrounds
  totalRP3/modules/register/characters/register_about.lua
Labels: bug

#429 Force dropdowns to avoid AddNewbieTip in 9.x
  totalRP3/core/impl/ui_tools.lua
Labels: bug

#432 Updating context after creating profile from default page
  totalRP3/modules/register/characters/register_main.lua
Labels: bug

#434 Side anchors on the default profile warning
  totalRP3/modules/register/characters/register_ui_main.xml
Labels: bug

#438 Fallback for C_PlayerInfo.GUIDIsPlayer
  totalRP3/modules/chatframe/prat.lua
Labels: bug

#435 Improve handling of improper case in /trp3 open
  totalRP3/modules/register/main/register_exchange.lua
Labels: enhancement

#442 Reference embedded libraries in pkgmeta
  .pkgmeta
Labels: third-party

#440 Migrate from Travis to GitHub Actions
  .github/actions/editorconfig-check/action.yml
  .github/workflows/PR-branch-check.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .luacheckrc
  .travis.yml
  Scripts/generate_luacheck_wowstd.sh
  Scripts/release.sh
Labels: enhancement

#444 Add LibChatAnims dependency
  .pkgmeta
  totalRP3/libs/LibChatAnims/LibChatAnims.lua
  totalRP3/libs/LibChatAnims/LibChatAnims.xml
  totalRP3/libs/libs.xml
Labels: bug

#453 Exit edit mode on Misc/Notes tabs
  totalRP3/modules/register/characters/register_misc.lua
  totalRP3/modules/register/characters/register_notes.lua
Labels: bug
