Repository Total-RP/Total-RP-3, pull requests merged in 2021-05, with the labels that each got.

#530 Burning Crusade Companion IDs
  totalRP3/resources/CompanionData.lua
Labels: enhancement

#534 TBC Packager Support
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .github/workflows/release_beta.yml
  totalRP3/totalRP3.toc
  totalRP3_Data/totalRP3_Data.toc
Labels: enhancement

#550 Remove heavy profile alert option
  totalRP3/core/impl/configuration.lua
  totalRP3/modules/register/main/register_exchange.lua
Labels: unenhancement

#563 Refresh directory list only when window is shown
  totalRP3/modules/register/main/register_list.lua
Labels: bug

#558 Clean up version check logic
  totalRP3/VersionCheck.lua
  totalRP3/__version.lua
  totalRP3/init.lua
  totalRP3/totalRP3.xml
Labels: unenhancement

#564 Add BCC client checks where needed
  .luacheckrc
  totalRP3/core/impl/AdvancedSettings.lua
  totalRP3/core/impl/communication_protocol_broadcast.lua
  totalRP3/core/impl/globals.lua
  totalRP3/core/impl/main_structure.lua
  totalRP3/core/ui/browsers/PetBrowser.lua
  totalRP3/modules/dashboard/dashboard.lua
  totalRP3/modules/map/Map.lua
  totalRP3/modules/register/characters/PlayerMapScan/PlayerMapPin.lua
  totalRP3/modules/register/characters/PlayerMapScan/PlayerMapScanner.lua
  totalRP3/modules/register/characters/register_characteristics.lua
  totalRP3/resources/imageList-classic.lua
  totalRP3/totalRP3.lua
Labels: enhancement

#567 Fix debug mode for Ellyb
  totalRP3/init.lua
Labels: bug

#565 Implement pooled queue strategy for profile comms
  .luacheckrc
  totalRP3/core/impl/AdvancedSettings.lua
  totalRP3/core/impl/CommunicationProtocol.lua
  totalRP3/modules/register/main/register_exchange.lua
  totalRP3/tools/Locale.lua
Labels: enhancement

#568 Fix nameplate updates on register changes
  totalRP3/modules/NamePlates/NamePlates_Core.lua
Labels: bug

#569 I am not a translator
  totalRP3/tools/Locale.lua
Labels: egregiously-bad-bug, quite-frankly-unplayable

#571 Fix incorrect vernum checks with profile exchange
  totalRP3/modules/register/main/register_exchange.lua
Labels: bug

#572 Throttle information requests from "bad" versions
  totalRP3/modules/register/main/register_exchange.lua
Labels: enhancement

#578 Added Classic checks for channel shenanigans
  totalRP3/core/impl/communication_protocol_broadcast.lua
Labels: bug
