Repository Total-RP/Total-RP-3, pull requests merged in 2021-04, with the labels that each got.

#551 April Fools cleanup
  totalRP3/core/impl/configuration.lua
  totalRP3/core/impl/globals.lua
  totalRP3/core/impl/main_structure.lua
  totalRP3/core/ui/main.xml
  totalRP3/modules/register/main/register_tooltip.lua
Labels: unenhancement

#547 9.1: Update power type global strings
  .luacheckrc
  totalRP3/core/impl/popup.lua
Labels: bug

#545 Hide trimmed Currently/OOC tooltip texts if empty
  totalRP3/modules/register/main/register_tooltip.lua
Labels: bug

#544 Protect "[TRP3:...]" links from chat transforms
  totalRP3/modules/chatframe/chatframe.lua
Labels: bug

#543 Fix mature tooltips overlapping GameTooltip
  totalRP3/modules/register/main/register_tooltip.lua
Labels: bug

#552 Added tooltip fields
  .luacheckrc
  totalRP3/modules/register/main/register_tooltip.lua
  totalRP3/tools/Locale.lua
Labels: enhancement

#538 Test for pets via UnitCreatureFamily
  .luacheckrc
  totalRP3/core/impl/ui_tools.lua
Labels: bug

#537 Route logging to _DebugLog if installed
  totalRP3/libs/Ellyb/Logs/Logger.lua
  totalRP3/totalRP3.toc
Labels: enhancement

#536 Make string cropping UTF-8 aware
  .luacheckrc
  .pkgmeta
  totalRP3/core/impl/utils.lua
  totalRP3/libs/UTF8/lib.xml
  totalRP3/libs/UTF8/utf8.lua
  totalRP3/libs/UTF8/utf8data.lua
  totalRP3/libs/libs.xml
  totalRP3/modules/register/main/register_tooltip.lua
Labels: bug

#535 Fix Kui names when level text/health is disabled
  totalRP3/modules/NamePlates/NamePlates_Kui.lua
  totalRP3/totalRP3.toc
Labels: bug

#554 Search VA field for "TotalRP3" in any position
  totalRP3/modules/register/msp/register_msp.lua
Labels: bug

#556 Don't create MSP profiles if VA field is empty
  totalRP3/modules/register/msp/register_msp.lua
Labels: bug

#555 Split profile information responses into queues
  .luacheckrc
  totalRP3/core/impl/CommunicationProtocol.lua
  totalRP3/modules/register/main/register_exchange.lua
Labels: enhancement

#557 Recursively unprotect string content
  totalRP3/modules/chatframe/chatframe.lua
Labels: bug
