Repository Total-RP/Total-RP-3, pull requests merged in 2022-11, with the labels that each got.

#644 Use C_TooltipInfo APIs for companion owner names
  .luacheckrc
  totalRP3/Core/UITools.lua
Labels: enhancement

#652 Cache configured locale in Data addon
  .luacheckrc
  totalRP3/Libs/Ellyb/Locales.lua
  totalRP3/Locales/Locale.lua
  totalRP3_Data/totalRP3_Data.lua
  totalRP3_Data/totalRP3_Data.toc
Labels: enhancement

#660 Allow opening profiles from player map scan pins
  .luacheckrc
  totalRP3/Core/Player.lua
  totalRP3/Locales/Locale.lua
  totalRP3/Modules/Map/MapPoiMixins.lua
  totalRP3/Modules/Register/Characters/PlayerMapScan/PlayerMapPin.lua
  totalRP3/Modules/Register/Characters/PlayerMapScan/PlayerMapScan.xml
Labels: enhancement

#665 Restrict the flow of information to the masses
  totalRP3/Core/CommunicationProtocol.lua
  totalRP3/Core/Compression.lua
  totalRP3/Libs/Ellyb/Documentation/Assertions.lua
  totalRP3/Libs/Ellyb/Documentation/DeprecationWarnings.lua
  totalRP3/Libs/Ellyb/Documentation/GameEvents.lua
  totalRP3/Libs/Ellyb/Documentation/_Documentation.lua
  totalRP3/Libs/Ellyb/Documentation/_Documentation.xml
  totalRP3/Libs/Ellyb/Ellyb.xml
Labels: unenhancement

#668 Added dracthyr icons for default profiles
  totalRP3/Resources/InterfaceIcons.lua
Labels: bug
