Repository Total-RP/Total-RP-3, pull requests merged in 2022-08, with the labels that each got.

#618 Allow basic "/trp3 profile" macro conditionals
  .luacheckrc
  totalRP3/core/impl/profiles.lua
Labels: enhancement

#617 Fix tooltip coloring with certain unicode inputs
  totalRP3/modules/register/main/register_tooltip.lua
Labels: bug

#610 Fix extraneous linebreaks after block elements
  totalRP3/core/impl/utils.lua
Labels: bug

#607 Tooltip text color customizations
  totalRP3/modules/register/main/register_tooltip.lua
  totalRP3/tools/Locale.lua
Labels: enhancement

#621 Sanitization improvements
  totalRP3/core/impl/utils.lua
  totalRP3/modules/dashboard/npc_talk.lua
  totalRP3/modules/register/characters/register_characteristics.lua
  totalRP3/modules/register/characters/register_misc.lua
Labels: enhancement

#625 Fix guild membership line tooltip nil errors
  totalRP3/modules/register/main/register_tooltip.lua
Labels: bug

#627 Add additional credits
  totalRP3/modules/dashboard/AboutTabView.lua
Labels: unenhancement

#629 Fix spurious crash when dragging Misc. Info fields
  totalRP3/modules/register/characters/register_characteristics.lua
Labels: bug
