Repository Total-RP/Total-RP-3, pull requests merged in 2022-05, with the labels that each got.

#604 Correctly update text area layout on size changes
  totalRP3/core/ui/widgets.lua
  totalRP3/core/ui/widgets.xml
Labels: bug

#601 Fix for target frame ElvUI skin
  totalRP3/modules/tooltip_skins/ElvUI.lua
Labels: bug

#577 Disallow nameplate requests for distant units
  .luacheckrc
  totalRP3/modules/NamePlates/NamePlates_Core.lua
  totalRP3/modules/NamePlates/NamePlates_RequestQueue.lua
  totalRP3/modules/NamePlates/NamePlates_Shared.lua
Labels: unenhancement

#546 Add customization of link colors in descriptions
  .luacheckrc
  totalRP3/core/impl/utils.lua
Labels: enhancement

#549 Profile sanitization improvements
  totalRP3/core/impl/AdvancedSettings.lua
  totalRP3/core/impl/utils.lua
  totalRP3/modules/register/characters/register_main.lua
Labels: unenhancement
