Repository Total-RP/Total-RP-3, pull requests merged in 2023-12, with the labels that each got.

#824 Customize own pet nameplate
  totalRP3/Modules/NamePlates/NamePlates_Core.lua
Labels: bug

#825 Safety for missing music title
  totalRP3/Modules/Register/Characters/RegisterAbout.lua
Labels: bug

#826 Update DisableAddOn usage for 10.2
  totalRP3/Modules/NamePlates/NamePlates_Kui.lua
Labels: bug

#828 Use MaskTextures instead of SetPortraitToTexture
  totalRP3/Core/Utils.lua
  totalRP3/Modules/Register/Main/RegisterGlance.lua
  totalRP3/Modules/Register/Main/RegisterUIGlance.xml
Labels: bug

#829 Clear additional fields on characteristics update
  totalRP3/Modules/Register/MSP/RegisterMSP.lua
Labels: bug

#830 Request PG, PR, and PV fields via MSP
  totalRP3/Modules/Register/MSP/Fields.lua
Labels: enhancement

#831 Winter cleaning
  totalRP3/Core/Utils.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Dashboard/Dashboard.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Characters/RegisterMain.lua
  totalRP3/Modules/Register/Characters/RegisterMisc.lua
  totalRP3/Resources/policegar.tga
Labels: unenhancement

#832 MSP sanitization
  totalRP3/Modules/Register/MSP/RegisterMSP.lua
Labels: unenhancement
