Repository Total-RP/Total-RP-3, pull requests merged in 2023-04, with the labels that each got.

#738 Migrate to C_AddOns.GetAddOnMetadata
  .luacheckrc
  totalRP3/Modules/Importer/MRP_API.lua
  totalRP3/Modules/Importer/XRP_API.lua
Labels: unenhancement

#737 Remove usage of C_CVar.RegisterCVar
  .luacheckrc
  totalRP3/Modules/Register/Companions/RegisterCompanionsMain.lua
Labels: unenhancement

#712 Implement 10.1 addon compartment integration
  totalRP3/Core/UIMain.lua
  totalRP3/Resources/trp3minimap.tga
  totalRP3/totalRP3.toc
  totalRP3_Data/totalRP3_Data.toc
Labels: enhancement

#739 Travis 3.0
  .editorconfig
  .gitattributes
  .github/workflows/locales.yml
  .github/workflows/pull_request.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  Makefile
  Scripts/UI.xsd
  totalRP3/Libs/Ellyb/Internals/Internals.xml
  totalRP3/Libs/MSA-DropDownMenu-1.0/MSA-DropDownMenu-1.0.lua
  totalRP3/Libs/MSA-DropDownMenu-1.0/MSA-DropDownMenu-1.0.xml
  totalRP3/Resources/resources.txt
Labels: enhancement

#742 Tweaks to nameplate visibility rules
  totalRP3/Modules/NamePlates/NamePlates_Core.lua
Labels: enhancement

#740 Use updated filename for LibRPMedia
  totalRP3/totalRP3.toc
Labels: unenhancement

#743 Party Time
  totalRP3/Core/Configuration.lua
  totalRP3/Core/MainStructure.lua
  totalRP3/Modules/Dashboard/Dashboard.lua
  totalRP3/Modules/Dashboard/Dashboard.xml
  totalRP3/Resources/fatcatparty.tga
  totalRP3/Resources/fatcatpat.tga
  totalRP3/Resources/fcp.tga
  totalRP3/UI/Main.xml
Labels: enhancement

#711 The great color rework
  .luacheckrc
  totalRP3/Core/AdvancedSettings.lua
  totalRP3/Core/Color.lua
  totalRP3/Core/ColorData.lua
  totalRP3/Core/Compression.lua
  totalRP3/Core/Configuration.lua
  totalRP3/Core/Core.xml
  totalRP3/Core/Globals.lua
  totalRP3/Core/Player.lua
  totalRP3/Core/Popup.lua
  totalRP3/Core/Profiles.lua
  totalRP3/Core/ProfilesChatLinksModule.lua
  totalRP3/Core/Slash.lua
  totalRP3/Core/UIMain.lua
  totalRP3/Core/UITools.lua
  totalRP3/Core/Utils.lua
  totalRP3/Libs/Ellyb/Tools/Colors.lua
  totalRP3/Libs/Ellyb/Tools/ColorsManager.lua
  totalRP3/Libs/Ellyb/Tools/Strings/Strings.lua
  totalRP3/Libs/Ellyb/Tools/Tools.xml
  totalRP3/Libs/Ellyb/UI/Popups.lua
  totalRP3/Libs/Ellyb/UI/Tooltip.lua
  totalRP3/Locales/Locale.lua
  totalRP3/Modules/ChatFrame/ChatFrame.lua
  totalRP3/Modules/ChatFrame/Prat.lua
  totalRP3/Modules/ChatFrame/WIM.lua
  totalRP3/Modules/ChatLinks/ChatLinkTooltipLines.lua
  totalRP3/Modules/ChatLinks/ChatLinks.lua
  totalRP3/Modules/Dashboard/NPCTalk.lua
  totalRP3/Modules/Dashboard/TabFrame.lua
  totalRP3/Modules/Flyway/FlywayPatches.lua
  totalRP3/Modules/Importer/Importer.lua
  totalRP3/Modules/Languages/Languages.lua
  totalRP3/Modules/Map/MapPoiMixins.lua
  totalRP3/Modules/Map/WorldMapButton.lua
  totalRP3/Modules/NamePlates/NamePlates_Blizzard.lua
  totalRP3/Modules/NamePlates/NamePlates_Core.lua
  totalRP3/Modules/NamePlates/NamePlates_Settings.lua
  totalRP3/Modules/Register/Characters/PlayerMapScan/PlayerMapPin.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Characters/RegisterIgnore.lua
  totalRP3/Modules/Register/Companions/CompanionProfileChatLinksModule.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsPage.lua
  totalRP3/Modules/Register/MSP/Fields.lua
  totalRP3/Modules/Register/Main/AtFirstGlanceChatLinksModule.lua
  totalRP3/Modules/Register/Main/RegisterCompanionChatLinksModule.lua
  totalRP3/Modules/Register/Main/RegisterList.lua
  totalRP3/Modules/Register/Main/RegisterPlayerChatLinksModule.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
  totalRP3/UI/Widgets.lua
  totalRP3/totalRP3.lua
  totalRP3/totalRP3.toc
Labels: enhancement

#725 Remove the English Language :peepoyeet:
  .editorconfig
  .github/workflows/locales.yml
  .github/workflows/update_translations.yml
  .gitignore
  .luacheckrc
  Makefile
  Scripts/generate-locales.sh
  Scripts/localization.py
  pyproject.toml
  requirements.txt
  totalRP3/Core/Popup.lua
  totalRP3/Core/Profiles.lua
  totalRP3/Core/UIMain.lua
  totalRP3/Core/UITools.lua
  totalRP3/Libs/Ellyb/Locales.lua
  totalRP3/Libs/Ellyb/Tools/Strings/Strings.lua
  totalRP3/Libs/Ellyb/Tools/System.lua
  totalRP3/Libs/Ellyb/Tools/Tools.xml
  totalRP3/Libs/Ellyb/UI/Popups.lua
  totalRP3/Locales/Locale.lua
  totalRP3/Locales/Locales.xml
  totalRP3/Locales/deDE.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/esES.lua
  totalRP3/Locales/esMX.lua
  totalRP3/Locales/frFR.lua
  totalRP3/Locales/itIT.lua
  totalRP3/Locales/koKR.lua
  totalRP3/Locales/ptBR.lua
  totalRP3/Locales/ruRU.lua
  totalRP3/Locales/zhCN.lua
  totalRP3/Locales/zhTW.lua
  totalRP3/Modules/Dashboard/Dashboard.lua
  totalRP3/Modules/Languages/Languages.lua
  totalRP3/Modules/Register/Characters/PlayerMapScan/PlayerMapPin.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
  totalRP3/Modules/Register/Main/RegisterCursor.lua
  totalRP3/Modules/Register/Main/RegisterGlance.lua
  totalRP3/Modules/Register/Main/RegisterList.lua
Labels: enhancement

#745 Fix incorrect callback registrations for nameplates
  totalRP3/Modules/NamePlates/NamePlates_Core.lua
Labels: bug

#733 Implement NSA backdoor
  .luacheckrc
  totalRP3/Core/Core.xml
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Analytics/Analytics.lua
  totalRP3/Modules/Analytics/Analytics.xml
  totalRP3/Modules/Analytics/Analytics_Data.lua
  totalRP3/Modules/Modules.xml
  totalRP3/totalRP3.toc
Labels: enhancement

#734 Add custom guild indicator and setting to disable in tooltips
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: enhancement

#746 Resolve merge issues with analytics
  totalRP3/Modules/Analytics/Analytics.lua
Labels: bug
