Repository Total-RP/Total-RP-3, pull requests merged in 2023-11, with the labels that each got.

#800 Make icon searching asynchronous
  .luacheckrc
  totalRP3/Core/Core.xml
  totalRP3/Core/Popup.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Resources/IconList.lua
  totalRP3/Resources/Resources.xml
  totalRP3/UI/Browsers/IconBrowser.lua
  totalRP3/UI/Browsers/IconBrowser.xml
  totalRP3/UI/Browsers/Icons.xml
Labels: enhancement

#753 Make nameplate settings less ambiguous
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Flyway/Flyway.lua
  totalRP3/Modules/Flyway/FlywayPatches.lua
  totalRP3/Modules/NamePlates/NamePlates_Core.lua
  totalRP3/Modules/NamePlates/NamePlates_Settings.lua
Labels: enhancement

#768 Rework launcher button integration
  .luacheckrc
  .pkgmeta
  totalRP3/Core/BindingUtil.lua
  totalRP3/Core/Configuration.lua
  totalRP3/Core/Core.xml
  totalRP3/Core/UIMain.lua
  totalRP3/Locales/Locale.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Flyway/FlywayPatches.lua
  totalRP3/Modules/Launcher/Launcher.lua
  totalRP3/Modules/Launcher/Launcher.xml
  totalRP3/Modules/Launcher/Launcher_Actions.lua
  totalRP3/Modules/Launcher/Launcher_Settings.lua
  totalRP3/Modules/Launcher/Launcher_Settings.xml
  totalRP3/Modules/Launcher/Launcher_Util.lua
  totalRP3/Modules/Modules.xml
  totalRP3/totalRP3.toc
Labels: enhancement

#788 Add support for automation profiles
  .luacheckrc
  .pkgmeta
  totalRP3/Core/StringUtil.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Automation/Automation.lua
  totalRP3/Modules/Automation/Automation_Settings.lua
  totalRP3/Modules/Automation/Automation_Settings.xml
  totalRP3/Modules/Automation/Automation_Util.lua
  totalRP3/totalRP3.toc
Labels: enhancement

#801 Broadcast and map scan improvements
  .luacheckrc
  totalRP3/Core/AdvancedSettings.lua
  totalRP3/Core/CommunicationProtocolBroadcast.lua
  totalRP3/Core/Globals.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Register/Characters/PlayerMapScan/PlayerMapScanner.lua
Labels: enhancement

#803 Persist window layout in configuration
  .pkgmeta
  totalRP3/Core/Configuration.lua
  totalRP3/Core/UIMain.lua
  totalRP3/UI/Main.lua
  totalRP3/UI/Main.xml
  totalRP3/totalRP3.toc
Labels: enhancement

#804 Pull libwindow from subdir
  .pkgmeta
Labels: bug

#805 Use correct event name
  totalRP3/Modules/Automation/Automation_Util.lua
Labels: bug

#806 More event fixups
  totalRP3/Modules/Automation/Automation_Util.lua
  totalRP3/UI/Browsers/IconBrowser.lua
Labels: bug

#807 Patch/unheck extended and its stupid choices
  totalRP3/UI/Main.lua
  totalRP3/UI/Main.xml
Labels: bug

#810 Update internal docs to reference new wiki
  totalRP3/Core/ColorData.lua
Labels: enhancement

#808 Support 10.2 changes to `GetAddOnEnableState`
  .luacheckrc
  totalRP3/Core/Utils.lua
  totalRP3/Modules/ModuleManagement.lua
  totalRP3/Modules/NamePlates/NamePlates_Blizzard.lua
  totalRP3/Modules/NamePlates/NamePlates_Kui.lua
  totalRP3/Modules/NamePlates/NamePlates_Plater.lua
Labels: bug

#809 Sort map scans by name in dropdown
  totalRP3/Modules/Map/MapScanner.lua
  totalRP3/Modules/Map/WorldMapButton.lua
  totalRP3/Modules/Register/Characters/PlayerMapScan/PlayerMapScanner.lua
Labels: enhancement

#811 Fix egregious skill issue
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: bug

#814 Loosen localization script version specifiers
  .github/scripts/requirements.txt
Labels: unenhancement

#818 Don't perform range tests in combat
  totalRP3/Modules/NamePlates/NamePlates_RequestQueue.lua
Labels: unenhancement

#819 Prat duplicate names on preset emotes
  totalRP3/Modules/ChatFrame/Prat.lua
Labels: bug
