Repository Total-RP/Total-RP-3, pull requests merged in 2023-02, with the labels that each got.

#690 Fix dashboard dropdowns displaying incorrect selected values
  totalRP3/Modules/Dashboard/StatusPanel.lua
Labels: bug

#686 Integrate LibDropDownExtension for UnitPopup module
  .pkgmeta
  totalRP3/Modules/UnitPopups/UnitPopups.lua
  totalRP3/totalRP3.toc
Labels: enhancement

#685 Persist name-only mode state in local settings
  .luacheckrc
  totalRP3/Modules/NamePlates/NamePlates_Blizzard.lua
  totalRP3/Modules/NamePlates/NamePlates_Shared.lua
Labels: enhancement

#691 Remove CTLDebug frame
  totalRP3/UI/Main.xml
Labels: unenhancement

#693 Update menu item texts on register data updates
  totalRP3/Modules/Register/Characters/RegisterMain.lua
Labels: bug

#694 More strict checks for profile existence
  totalRP3/Modules/Register/Characters/RegisterMain.lua
Labels: bug

#657 Plater Nameplates Support
  .luacheckrc
  totalRP3/Locales/Locale.lua
  totalRP3/Modules/ModuleManagement.lua
  totalRP3/Modules/NamePlates/NamePlates.xml
  totalRP3/Modules/NamePlates/NamePlates_Plater.lua
  totalRP3/Modules/NamePlates/NamePlates_Shared.lua
Labels: enhancement

#700 Plater Module Day 1 Patch Part 2
  totalRP3/Modules/NamePlates/NamePlates_Plater.lua
Labels: bug

#699 Additional toolbar visibility options
  CHANGELOG.md
  totalRP3/Core/Events.lua
  totalRP3/Locales/Locale.lua
  totalRP3/Modules/Dashboard/Dashboard.lua
  totalRP3/Modules/Flyway/Flyway.lua
  totalRP3/Modules/Flyway/FlywayPatches.lua
  totalRP3/Modules/TargetFrame/TargetFrame.lua
  totalRP3/Modules/Toolbar/Toolbar.lua
Labels: enhancement

#703 Fix "Unknown" target names in tooltips
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: bug
