Repository Total-RP/Total-RP-3, pull requests merged in 2023-05, with the labels that each got.

#747 Misc. Classic Fixups
  .luacheckrc
  totalRP3/Core/ColorData.lua
  totalRP3/Modules/Languages/Languages.lua
Labels: bug

#735 Profile automation
  .luacheckrc
  totalRP3/Core/Automation.lua
  totalRP3/Core/Configuration.lua
  totalRP3/Core/Core.xml
  totalRP3/Core/Profiles.lua
  totalRP3/Core/StringUtil.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Automation/Automation.lua
  totalRP3/Modules/Automation/Automation.xml
  totalRP3/Modules/Automation/Automation_Actions.lua
  totalRP3/Modules/Automation/Automation_Conditions.lua
  totalRP3/Modules/Automation/Automation_FieldSetters.lua
  totalRP3/Modules/Automation/Automation_Settings.lua
  totalRP3/Modules/Automation/Automation_Settings.xml
  totalRP3/Modules/Automation/Automation_Util.lua
  totalRP3/Modules/Dashboard/Dashboard.lua
  totalRP3/Modules/Modules.xml
  totalRP3/Modules/Register/Characters/PlayerMapScan/PlayerMapScanner.lua
  totalRP3/UI/FocusRegion.lua
  totalRP3/UI/FocusRegion.xml
  totalRP3/UI/UIButton.lua
  totalRP3/UI/UIButton.xml
  totalRP3/UI/Widgets.xml
  totalRP3/totalRP3.toc
Labels: enhancement

#741 Update Plater mod and move nameplate customization to TRP3
  .luacheckrc
  totalRP3/Modules/NamePlates/NamePlates_Plater.lua
Labels: enhancement

#748 Don't explode on nil frame names
  totalRP3/Modules/NamePlates/NamePlates_Blizzard.lua
Labels: bug

#750 Fix configuration error with analytics
  totalRP3/Modules/Analytics/Analytics.lua
Labels: bug

#752 Bump flyway schema version
  totalRP3/Modules/Flyway/Flyway.lua
Labels: bug

#763 Fix lookup for colors in chat links
  totalRP3/Modules/ChatLinks/ChatLinks.lua
Labels: bug

#759 Default guild rank text on display
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: unenhancement

#758 Don't expect color markup in player name strings
  totalRP3/Modules/ChatFrame/Prat.lua
Labels: bug

#765 Plater mod bug fixes
  totalRP3/Modules/NamePlates/NamePlates_Plater.lua
Labels: bug

#772 Trigger guild fallback on empty custom names
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: unenhancement

#771 Better handling of guild names in nameplates
  totalRP3/Modules/NamePlates/NamePlates_Core.lua
Labels: enhancement

#775 Wake up Sol, new taintless just dropped
  totalRP3/Libs/TaintLess/TaintLess.xml
Labels: third-party
