Repository Total-RP/Total-RP-3, pull requests merged in 2023-03, with the labels that each got.

#705 Localization fixups
  totalRP3/Locales/Locale.lua
Labels: bug

#702 NPC nameplate support and additional settings
  totalRP3/Core/Globals.lua
  totalRP3/Locales/Locale.lua
  totalRP3/Modules/NamePlates/NamePlates.xml
  totalRP3/Modules/NamePlates/NamePlates_Blizzard.lua
  totalRP3/Modules/NamePlates/NamePlates_Core.lua
  totalRP3/Modules/NamePlates/NamePlates_Kui.lua
  totalRP3/Modules/NamePlates/NamePlates_Plater.lua
  totalRP3/Modules/NamePlates/NamePlates_RequestQueue.lua
  totalRP3/Modules/NamePlates/NamePlates_Settings.lua
  totalRP3/Modules/NamePlates/NamePlates_Shared.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: enhancement

#704 Add guild name/rank misc. info presets
  totalRP3/Core/Core.xml
  totalRP3/Core/Player.lua
  totalRP3/Core/ProfileUtil.lua
  totalRP3/Core/Utils.lua
  totalRP3/Init.lua
  totalRP3/Locales/Locale.lua
  totalRP3/Modules/Flyway/Flyway.lua
  totalRP3/Modules/Flyway/FlywayPatches.lua
  totalRP3/Modules/Importer/MRP_API.lua
  totalRP3/Modules/Importer/XRP_API.lua
  totalRP3/Modules/NamePlates/NamePlates_Core.lua
  totalRP3/Modules/NamePlates/NamePlates_Settings.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/MSP/RegisterMSP.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
  totalRP3/Resources/InterfaceIcons.lua
  totalRP3/totalRP3.xml
Labels: enhancement

#708 Remove (mostly) unused Ellyb facilities
  .luacheckrc
  totalRP3/Core/CommunicationProtocol.lua
  totalRP3/Core/Profiles.lua
  totalRP3/Libs/Ellyb/Configuration/Configuration.lua
  totalRP3/Libs/Ellyb/Ellyb.xml
  totalRP3/Libs/Ellyb/Enum.lua
  totalRP3/Libs/Ellyb/Internals/Internals.xml
  totalRP3/Libs/Ellyb/Internals/PooledObjectMixin.lua
  totalRP3/Libs/Ellyb/Libraries/Libraries.xml
  totalRP3/Libs/Ellyb/Libraries/easings.lua
  totalRP3/Libs/Ellyb/Locales.lua
  totalRP3/Libs/Ellyb/Logs/Log.lua
  totalRP3/Libs/Ellyb/Tools/Colors.lua
  totalRP3/Libs/Ellyb/Tools/ColorsManager.lua
  totalRP3/Libs/Ellyb/Tools/DeprecationWarnings.lua
  totalRP3/Libs/Ellyb/Tools/EventsDispatcher.lua
  totalRP3/Libs/Ellyb/Tools/Functions.lua
  totalRP3/Libs/Ellyb/Tools/Maths.lua
  totalRP3/Libs/Ellyb/Tools/Promise.lua
  totalRP3/Libs/Ellyb/Tools/Promises.lua
  totalRP3/Libs/Ellyb/Tools/SlashCommand.lua
  totalRP3/Libs/Ellyb/Tools/Strings/Interpolate.lua
  totalRP3/Libs/Ellyb/Tools/Strings/Strings.lua
  totalRP3/Libs/Ellyb/Tools/System.lua
  totalRP3/Libs/Ellyb/Tools/Tables.lua
  totalRP3/Libs/Ellyb/Tools/Thread.lua
  totalRP3/Libs/Ellyb/Tools/Threads.lua
  totalRP3/Libs/Ellyb/Tools/Tools.xml
  totalRP3/Libs/Ellyb/Tools/Transitionators.lua
  totalRP3/Libs/Ellyb/Tools/Unit.lua
  totalRP3/Libs/Ellyb/UI/EditBoxes.lua
  totalRP3/Libs/Ellyb/UI/Frames.lua
  totalRP3/Libs/Ellyb/UI/Popups.xml
  totalRP3/Libs/Ellyb/UI/UI.xml
  totalRP3/Locales/Locale.lua
  totalRP3/Modules/ChatFrame/ChatFrame.lua
  totalRP3/Modules/ChatLinks/ChatLinkActionButton.lua
  totalRP3/Modules/Dashboard/WhatsNewTabView.lua
  totalRP3/Modules/Map/MapScanner.lua
  totalRP3/Modules/Map/MapScannersManager.lua
  totalRP3/Modules/Map/WorldMapButton.lua
  totalRP3/Modules/Register/Characters/RegisterMain.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
  totalRP3/Modules/Register/Filter/RegisterMatureFilter.lua
  totalRP3/Modules/Register/MSP/Fields.lua
  totalRP3/Modules/Register/Main/AtFirstGlanceChatLinksModule.lua
  totalRP3/Modules/Register/Main/RegisterGlance.lua
  totalRP3/Modules/Register/Main/RegisterList.lua
Labels: enhancement

#709 Rework logging infrastructure
  .luacheckrc
  totalRP3/Core/CommunicationProtocol.lua
  totalRP3/Core/CommunicationProtocolBroadcast.lua
  totalRP3/Core/Core.xml
  totalRP3/Core/Events.lua
  totalRP3/Core/Globals.lua
  totalRP3/Core/Logging.lua
  totalRP3/Core/MainStructure.lua
  totalRP3/Core/Utils.lua
  totalRP3/Libs/Ellyb/Ellyb.lua
  totalRP3/Libs/Ellyb/Ellyb.xml
  totalRP3/Libs/Ellyb/Logs/Log.lua
  totalRP3/Libs/Ellyb/Logs/Logger.lua
  totalRP3/Libs/Ellyb/Logs/Logs.xml
  totalRP3/Libs/Ellyb/Logs/LogsManager.lua
  totalRP3/Libs/Ellyb/Tools/EventsDispatcher.lua
  totalRP3/Libs/Ellyb/Tools/GameEvents.lua
  totalRP3/Libs/Ellyb/UI/Cursor.lua
  totalRP3/Locales/Locale.lua
  totalRP3/Modules/Flyway/Flyway.lua
  totalRP3/Modules/Importer/Importer.lua
  totalRP3/Modules/Languages/Languages.lua
  totalRP3/Modules/ModuleManagement.lua
  totalRP3/Modules/Register/Characters/RegisterMain.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsMain.lua
  totalRP3/Modules/Register/Filter/RegisterMatureFilter.lua
  totalRP3/Modules/Register/MSP/Fields.lua
  totalRP3/Modules/Register/Main/RegisterExchange.lua
  totalRP3/totalRP3.lua
Labels: enhancement

#717 Use KuiNameplates fader for nameplate visibility
  totalRP3/Modules/NamePlates/NamePlates_Kui.lua
Labels: bug

#719 Relocate 'toggle your stuff' message to header
  totalRP3/Locales/Locale.lua
  totalRP3/Modules/NamePlates/NamePlates_Settings.lua
Labels: unenhancement

#723 Resolve missing guild rank icon for Classic Era
  totalRP3/Resources/InterfaceIcons.lua
Labels: bug

#718 Add support for guild names to KNP decorator
  totalRP3/Locales/Locale.lua
  totalRP3/Modules/NamePlates/NamePlates_Kui.lua
Labels: enhancement

#724 Remove inaccessible icons table
  totalRP3/Resources/InterfaceIcons.lua
Labels: unenhancement

#727 Update Plater mod to support custom guild names and nameplate updates
  totalRP3/Modules/NamePlates/NamePlates_Plater.lua
Labels: enhancement

#728 Expose original guild strings to nameplates
  totalRP3/Modules/NamePlates/NamePlates_Core.lua
Labels: enhancement

#730 Remove throttle for super old versions
  .luacheckrc
  totalRP3/Modules/Register/Main/RegisterExchange.lua
Labels: unenhancement
