Repository Total-RP/Total-RP-3, pull requests merged in 2024-05, with the labels that each got.

#866 Update phased zone constants for garrisons
  totalRP3/Modules/Map/Map.lua
Labels: bug

#867 Use displayed map ID for culling
  totalRP3/Modules/Map/Map.lua
  totalRP3/Modules/Register/Characters/PlayerMapScan/PlayerMapScanner.lua
Labels: bug

#869 Fix the worst ever error in a tooltip
  totalRP3/Locales/enUS.lua
Labels: bug

#870 Add manual workflow for force-uploading translations
  .github/scripts/localization.py
  .github/workflows/upload_all_translations.yml
  Makefile
Labels: enhancement

#876 Hide the spinner on companion tooltips
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: bug

#875 Add 'Open Profile' option to pet menus
  totalRP3/Modules/UnitPopups/UnitPopups.lua
Labels: enhancement

#877 Re-add support for linking companions on Classic
  .luacheckrc
  totalRP3/Core/Popup.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Resources/CompanionData.lua
  totalRP3/UI/Browsers/Companions.xml
Labels: bug

#879 Update MSA and TaintLess libraries
  totalRP3/Libs/MSA-DropDownMenu-1.0/MSA-DropDownMenu-1.0.lua
  totalRP3/Libs/MSA-DropDownMenu-1.0/MSA-DropDownMenu-1.0.xml
  totalRP3/Libs/TaintLess/TaintLess.xml
Labels: enhancement

#880 Add TaintLess to pkgmeta
  .gitignore
  .pkgmeta
  totalRP3/Libs/TaintLess/TaintLess.xml
Labels: unenhancement

#881 Fix batch uploading of locales
  .github/scripts/localization.py
  .github/scripts/requirements.txt
  .github/workflows/update_translations.yml
  .github/workflows/upload_all_translations.yml
  Makefile
Labels: bug, duplicate, enhancement, help wanted, invalid, question, wontfix, third-party, companions, fixed, LibMSP, unenhancement, dependencies

#883 Add 'Open Profile' option to Battle.net friends
  .luacheckrc
  totalRP3/Modules/UnitPopups/UnitPopups.lua
Labels: enhancement

#884 Defer fade rule registration until plugin enabled
  totalRP3/Modules/NamePlates/NamePlates_Kui.lua
Labels: bug

#885 Adjust clamp insets when mount tooltip is shown
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: bug

#887 Restore the Timerunner icon on customized chat names
  .luacheckrc
  totalRP3/Modules/ChatFrame/ChatFrame.lua
Labels: bug

#890 Wrap companion mount titles in tooltips
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: bug

#889 Add soft target support for tooltips
  .luacheckrc
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: enhancement

#888 Defer Launcher event registrations to OnInitialize
  totalRP3/Modules/Launcher/Launcher.lua
Labels: bug

#893 Avoid rare errors in tooltip SetPoint calls
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: bug
