Repository Total-RP/Total-RP-3, pull requests merged in 2024-01, with the labels that each got.

#835 Misc preset renaming issues
  totalRP3/Core/ProfileUtil.lua
  totalRP3/Core/Profiles.lua
  totalRP3/Modules/Flyway/Flyway.lua
  totalRP3/Modules/Flyway/FlywayPatches.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Characters/RegisterUICharacteristics.xml
Labels: bug, enhancement

#815 Use labelled binding categories instead of headers
  totalRP3/Bindings.xml
Labels: bug, enhancement, wontfix, unenhancement

#822 Fix unit frame 'open profile' button
  totalRP3/Modules/Register/Main/RegisterExchange.lua
Labels: bug

#839 Check type of textKey field, not value
  totalRP3/UI/LocalizedText.lua
Labels: bug

#841 Make icons larger again
  totalRP3/Modules/Register/Main/RegisterGlance.lua
  totalRP3/UI/Browsers/IconBrowser.lua
  totalRP3/UI/Browsers/IconBrowser.xml
Labels: enhancement
