Repository Total-RP/Total-RP-3, pull requests merged in 2024-06, with the labels that each got.

#899 Migrate to C_Spell.GetSpellInfo for 11.0
  .luacheckrc
  totalRP3/Modules/Register/Companions/RegisterCompanionsMain.lua
  totalRP3/Resources/CompanionData.lua
Labels: unenhancement

#901 Add 20 new profile backgrounds
  totalRP3/Core/UITools.lua
Labels: enhancement

#897 Avoid customizing tooltips if GTT is unowned
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: bug

#895 ElvUI default tooltip anchoring
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
  totalRP3/Modules/TooltipSkins/ElvUI.lua
Labels: enhancement

#896 Remove use of deprecated PetCanBeRenamed API
  .luacheckrc
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
Labels: unenhancement

#900 Migrate to new menu system
  .github/workflows/pull_request.yml
  .gitignore
  .luacheckrc
  .pkgmeta
  .pre-commit-config.yaml
  totalRP3/Core/Configuration.lua
  totalRP3/Core/UITools.lua
  totalRP3/Deprecated.lua
  totalRP3/Deprecated.xml
  totalRP3/Libs/MSA-DropDownMenu-1.0/MSA-DropDownMenu-1.0.lua
  totalRP3/Libs/MSA-DropDownMenu-1.0/MSA-DropDownMenu-1.0.xml
  totalRP3/Modules/Automation/Automation_Settings.lua
  totalRP3/Modules/Automation/Automation_Settings.xml
  totalRP3/Modules/Dashboard/Dashboard.xml
  totalRP3/Modules/Dashboard/StatusPanel.lua
  totalRP3/Modules/Dashboard/StatusPanel.xml
  totalRP3/Modules/Register/Characters/PlayerMapScan/PlayerMapPin.lua
  totalRP3/Modules/Register/Characters/PlayerMapScan/PlayerMapScan.xml
  totalRP3/Modules/Register/Characters/RegisterUIAbout.xml
  totalRP3/Modules/Register/Characters/RegisterUICharacteristics.xml
  totalRP3/Modules/Register/Characters/RegisterUIMisc.xml
  totalRP3/Modules/Register/Companions/RegisterUICompanionsPage.xml
  totalRP3/Modules/UnitPopups/UnitPopups.lua
  totalRP3/UI/Configuration.xml
  totalRP3/UI/Menu/DropdownButton.xml
  totalRP3/UI/Menu/DropdownButton_Legacy.lua
  totalRP3/UI/Menu/DropdownButton_Modern.lua
  totalRP3/UI/Menu/DropdownButton_Shared.lua
  totalRP3/UI/Menu/Menu.lua
  totalRP3/UI/Menu/Menu.xml
  totalRP3/UI/Menu/MenuConstants.lua
  totalRP3/UI/Menu/MenuTemplates.lua
  totalRP3/UI/Menu/MenuTest.lua
  totalRP3/UI/Menu/MenuUtil.lua
  totalRP3/UI/Widgets.xml
  totalRP3/totalRP3.toc
Labels: enhancement

#898 Prefer securecall for non-fatal error dispatch
  .luacheckrc
  totalRP3/Core/Popup.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/ModuleManagement.lua
  totalRP3/Resources/InterfaceIcons.lua
  totalRP3/UI/Browsers/PetBrowser.lua
Labels: unenhancement

#902 Check launcher action validity for tooltip instructions
  totalRP3/Modules/Launcher/Launcher.lua
Labels: bug

#908 Show RP names in dice roll output
  totalRP3/Core/Slash.lua
Labels: enhancement

#909 Currently deserves to be framed.
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Dashboard/Currently.lua
  totalRP3/Modules/Dashboard/Currently.xml
  totalRP3/Modules/Dashboard/Dashboard.xml
  totalRP3/Resources/InterfaceIcons.lua
Labels: enhancement

#910 Make NPCTalk and Currently frames toplevel
  totalRP3/Modules/Dashboard/Currently.xml
  totalRP3/Modules/Dashboard/Dashboard.xml
Labels: bug

#907 We call these fields "statuses" in TRP, name them so + cleanup
  totalRP3/Locales/deDE.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/esES.lua
  totalRP3/Locales/esMX.lua
  totalRP3/Locales/frFR.lua
  totalRP3/Locales/ptBR.lua
  totalRP3/Locales/ruRU.lua
  totalRP3/Locales/zhCN.lua
  totalRP3/Locales/zhTW.lua
  totalRP3/Modules/Register/Characters/RegisterMisc.lua
  totalRP3/Modules/Register/Main/RegisterPlayerChatLinksModule.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: enhancement

#914 Remove UI sound and animation settings
  totalRP3/Core/Configuration.lua
  totalRP3/Core/UITools.lua
  totalRP3/Modules/Map/MapPoiMixins.lua
Labels: unenhancement

#913 Export localization strings globally
  totalRP3/Libs/Ellyb/Tools/Locale.lua
  totalRP3/Libs/Ellyb/Tools/Localization.lua
  totalRP3/Locales/Locale.lua
Labels: unenhancement

#904 Misc. Dropdown Fixups
  totalRP3/Modules/Automation/Automation_Settings.lua
  totalRP3/Modules/Dashboard/StatusPanel.lua
  totalRP3/UI/Menu/DropdownButton_Legacy.lua
  totalRP3/UI/Menu/DropdownButton_Modern.lua
  totalRP3/UI/Menu/Menu.lua
Labels: bug

#915 Adjust fonts without breaking alphabet swaps
  .luacheckrc
  totalRP3/Core/UITools.lua
  totalRP3/Modules/ChatLinks/ChatLinkTooltip.lua
  totalRP3/Modules/NamePlates/NamePlates_Kui.lua
  totalRP3/Modules/Register/Characters/RegisterAbout.lua
Labels: bug

#916 Remove info tooltip size setting
  totalRP3/Core/Configuration.lua
  totalRP3/Core/MainStructure.lua
  totalRP3/Core/UITools.lua
Labels: unenhancement

#918 Eliminate egregious and undesirable upvalues
  totalRP3/Core/CommunicationProtocolBroadcast.lua
  totalRP3/Core/Configuration.lua
  totalRP3/Core/MainStructure.lua
  totalRP3/Core/Popup.lua
  totalRP3/Core/Profiles.lua
  totalRP3/Core/Slash.lua
  totalRP3/Core/UITools.lua
  totalRP3/Modules/ChatFrame/ChatFrame.lua
  totalRP3/Modules/ChatLinks/ChatLinkModule.lua
  totalRP3/Modules/Dashboard/Dashboard.lua
  totalRP3/Modules/Dashboard/HTMLContent.lua
  totalRP3/Modules/Dashboard/NPCTalk.lua
  totalRP3/Modules/Dashboard/TabFrame.lua
  totalRP3/Modules/Dashboard/TabView.lua
  totalRP3/Modules/Dashboard/WhatsNewTabView.lua
  totalRP3/Modules/Flyway/Flyway.lua
  totalRP3/Modules/Importer/Importer.lua
  totalRP3/Modules/ModuleManagement.lua
  totalRP3/Modules/Register/Characters/PlayerMapScan/PlayerMapScanner.lua
  totalRP3/Modules/Register/Characters/RegisterAbout.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Characters/RegisterIgnore.lua
  totalRP3/Modules/Register/Characters/RegisterMain.lua
  totalRP3/Modules/Register/Characters/RegisterMisc.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsMain.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
  totalRP3/Modules/Register/Main/RegisterCursor.lua
  totalRP3/Modules/Register/Main/RegisterExchange.lua
  totalRP3/Modules/Register/Main/RegisterGlance.lua
  totalRP3/Modules/Register/Main/RegisterList.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
  totalRP3/Modules/TargetFrame/TargetFrame.lua
Labels: unenhancement

#919 Guard against attempts to animate the void
  totalRP3/Core/UITools.lua
Labels: bug

#920 Misc. Tooltip Fixups
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: bug, enhancement
