Repository Total-RP/Total-RP-3, pull requests merged in 2024-03, with the labels that each got.

#847 Check for invalid companion IDs in nameplates
  totalRP3/Modules/NamePlates/NamePlates_Core.lua
Labels: bug

#846 Fix error when displaying ignored companion tooltip
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: bug

#845 Check last scanner used
  totalRP3/Modules/Register/Characters/PlayerMapScan/PlayerMapScanner.lua
Labels: unenhancement

#844 Fix handling of unknown music names
  totalRP3/Core/Utils.lua
Labels: bug

#848 Don't send MSP requests for pets on mouseover
  totalRP3/Modules/Register/MSP/RegisterMSP.lua
Labels: unenhancement

#849 Don't wait forever on data that's not coming
  totalRP3/Modules/Register/Main/RegisterExchange.lua
Labels: bug

#850 Simplify object prototype system
  totalRP3/Core/Color.lua
  totalRP3/Core/Objects/Callback.lua
  totalRP3/Core/Objects/CallbackGroup.lua
  totalRP3/Core/Objects/CallbackGroupCollection.lua
  totalRP3/Core/Objects/CallbackRegistry.lua
  totalRP3/Core/Prototype.lua
  totalRP3/Modules/Analytics/Analytics.lua
  totalRP3/Modules/Automation/Automation.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
  totalRP3/UI/Browsers/IconBrowser.lua
Labels: unenhancement

#851 Fix numeric sequencing of chat links
  totalRP3/Modules/ChatLinks/ChatLinksManager.lua
Labels: bug

#853 Hide the chat link duplicate prevention ID
  totalRP3/Modules/ChatLinks/ChatLinks.lua
  totalRP3/Modules/ChatLinks/ChatLinksManager.lua
Labels: enhancement

#854 Update GH Action Versions
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .github/workflows/release_beta.yml
  .github/workflows/update_translations.yml
  .luacheckrc
  totalRP3/Core/Configuration.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
  totalRP3/Resources/option1.tga
  totalRP3/Resources/option2.tga
  totalRP3/Resources/option3.tga
  totalRP3/Resources/option4.tga
Labels: unenhancement

#855 Don't exceed 60 upvalue limit in tooltip builder
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: bug
