Repository Total-RP/Total-RP-3, pull requests merged in 2024-07, with the labels that each got.

#923 Use overridable default tooltip anchoring function
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: bug

#924 Fix KuiNameplates error when customization module is disabled
  totalRP3/Modules/NamePlates/NamePlates_Kui.lua
Labels: bug

#926 Make default RP status OOC
  totalRP3/Modules/Dashboard/Dashboard.lua
  totalRP3/Modules/Flyway/Flyway.lua
  totalRP3/Modules/Flyway/FlywayPatches.lua
Labels: unenhancement

#929 Center RP style options on large window sizes
  totalRP3/Modules/Register/Characters/RegisterMisc.lua
  totalRP3/Modules/Register/Characters/RegisterUIMisc.xml
Labels: unenhancement

#930 Add icons for Earthen race
  totalRP3/Resources/InterfaceIcons.lua
Labels: enhancement

#931 Use pluralization grammar sequences
  totalRP3/Locales/enUS.lua
Labels: enhancement

#928 Directory character list tutorial rework.
  totalRP3/Locales/deDE.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/esES.lua
  totalRP3/Locales/frFR.lua
  totalRP3/Locales/ptBR.lua
  totalRP3/Locales/ruRU.lua
  totalRP3/Locales/zhCN.lua
  totalRP3/Modules/Register/Main/RegisterList.lua
  totalRP3/Modules/Register/Main/RegisterUIList.xml
Labels: enhancement

#932 Add utilities for creating markup strings
  totalRP3/Core/Core.xml
  totalRP3/Core/MarkupUtil.lua
Labels: enhancement

#934 Misc. code cleanups
  totalRP3/Core/Configuration.lua
  totalRP3/Core/ProfileUtil.lua
Labels: unenhancement

#935 Add GetCustomClass/Race methods to Player class
  totalRP3/Core/Player.lua
Labels: enhancement

#936 Tweak formatting of instruction texts
  totalRP3/Locales/Locale.lua
  totalRP3/Locales/enUS.lua
Labels: enhancement

#933 Add utilities for ratio-preserving texture resizes
  .luacheckrc
  totalRP3/Core/Core.xml
  totalRP3/Core/RegionUtil.lua
  totalRP3/UI/RegionResizeTemplate.lua
  totalRP3/UI/RegionResizeTemplate.xml
  totalRP3/UI/Widgets.xml
Labels: enhancement

#939 Use our tooltip for menus
  totalRP3/UI/Menu/MenuUtil.lua
Labels: bug

#940 Center Status panel on dashboard
  totalRP3/Modules/Dashboard/StatusPanel.xml
Labels: enhancement

#927 Make RP experience a global setting
  totalRP3/Core/Enums.lua
  totalRP3/Core/Player.lua
  totalRP3/Core/ProfileUtil.lua
  totalRP3/Core/Profiles.lua
  totalRP3/Locales/deDE.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/esES.lua
  totalRP3/Locales/esMX.lua
  totalRP3/Locales/frFR.lua
  totalRP3/Locales/ptBR.lua
  totalRP3/Locales/ruRU.lua
  totalRP3/Locales/zhCN.lua
  totalRP3/Locales/zhTW.lua
  totalRP3/Modules/Dashboard/Dashboard.lua
  totalRP3/Modules/Dashboard/StatusPanel.lua
  totalRP3/Modules/Flyway/Flyway.lua
  totalRP3/Modules/Flyway/FlywayPatches.lua
  totalRP3/Modules/Register/Characters/RegisterMain.lua
  totalRP3/Modules/Register/Characters/RegisterMisc.lua
  totalRP3/Modules/Register/Characters/RegisterUIMisc.xml
  totalRP3/Modules/Register/MSP/RegisterMSP.lua
  totalRP3/Modules/Register/Main/RegisterExchange.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: enhancement

#945 Fix progress spinner wobble
  totalRP3/Modules/Register/Characters/RegisterUIMain.xml
Labels: bug

#947 Remove glance icon from tooltip
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: unenhancement

#946 Enable missing phrase deletion for locale uploads
  Makefile
Labels: help wanted, unenhancement

#948 Well that was an unmitigated fucking disaster
  Makefile
Labels: enhancement

#955 Improve import and export of translation strings
  .github/workflows/export-all-translations.yml
  .github/workflows/export-translations.yml
  .github/workflows/import-translations.yml
  Makefile
Labels: unenhancement

#952 Avoid potential asserts in GetRoleplayExperience
  totalRP3/Core/Player.lua
Labels: bug

#954 zhTW locale fixes
  totalRP3/Locales/zhTW.lua
Labels: bug

#950 Misc. UI Tweaks
  totalRP3/Core/Events.lua
  totalRP3/Modules/Dashboard/AboutTabView.lua
  totalRP3/Modules/Dashboard/ModulesTabView.lua
  totalRP3/Modules/Register/Characters/RegisterAbout.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Characters/RegisterMain.lua
  totalRP3/Modules/Register/Characters/RegisterUIAbout.xml
  totalRP3/Modules/Register/Companions/RegisterCompanionsPage.lua
  totalRP3/UI/Browsers/IconBrowser.lua
  totalRP3/UI/Browsers/IconBrowser.xml
Labels: bug, enhancement, unenhancement

#953 Misc roleplay styles revamp + tooltips updated consistency
  totalRP3/Locales/deDE.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/esES.lua
  totalRP3/Locales/esMX.lua
  totalRP3/Locales/frFR.lua
  totalRP3/Locales/itIT.lua
  totalRP3/Locales/ptBR.lua
  totalRP3/Locales/ruRU.lua
  totalRP3/Locales/zhCN.lua
  totalRP3/Locales/zhTW.lua
  totalRP3/Modules/Register/Characters/RegisterMisc.lua
Labels: enhancement

#960 Rename Masters to Owners
  totalRP3/Locales/enUS.lua
Labels: bug

#963 Relationship adjustments
  totalRP3/Locales/deDE.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/esES.lua
  totalRP3/Locales/esMX.lua
  totalRP3/Locales/frFR.lua
  totalRP3/Locales/ptBR.lua
  totalRP3/Locales/ruRU.lua
  totalRP3/Locales/zhCN.lua
  totalRP3/Locales/zhTW.lua
  totalRP3/Modules/Register/Characters/RegisterIgnore.lua
  totalRP3/Modules/Register/Characters/RegisterRelations.lua
  totalRP3/Modules/Register/Characters/RegisterUICharacteristics.xml
Labels: enhancement

#965 Update the target frame buttons
  totalRP3/Modules/TargetFrame/TargetFrame.lua
  totalRP3/Modules/TargetFrame/TargetFrame.xml
Labels: enhancement

#967 Add character class ID to exchange
  totalRP3/Modules/Register/Characters/RegisterMain.lua
  totalRP3/Modules/Register/Main/RegisterExchange.lua
Labels: enhancement

#944 Export RP style options via MSP
  totalRP3/Modules/Register/Characters/RegisterMisc.lua
  totalRP3/Modules/Register/MSP/RegisterMSP.lua
Labels: enhancement

#959 Add icon right-click options (copy icon, icon name, paste icon)
  totalRP3/Locales/deDE.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/esES.lua
  totalRP3/Locales/frFR.lua
  totalRP3/Locales/itIT.lua
  totalRP3/Locales/ptBR.lua
  totalRP3/Locales/ruRU.lua
  totalRP3/Locales/zhCN.lua
  totalRP3/Locales/zhTW.lua
  totalRP3/Modules/Register/Characters/RegisterAbout.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsPage.lua
  totalRP3/Modules/Register/Main/RegisterGlance.lua
  totalRP3/UI/Widgets.lua
Labels: enhancement

#966 Update target frame tooltips and companion icons
  totalRP3/Locales/deDE.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/esES.lua
  totalRP3/Locales/esMX.lua
  totalRP3/Locales/frFR.lua
  totalRP3/Locales/itIT.lua
  totalRP3/Locales/ptBR.lua
  totalRP3/Locales/ruRU.lua
  totalRP3/Locales/zhCN.lua
  totalRP3/Locales/zhTW.lua
  totalRP3/Modules/Register/Characters/RegisterIgnore.lua
  totalRP3/Modules/Register/Characters/RegisterNotes.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
  totalRP3/Modules/Register/Main/RegisterList.lua
  totalRP3/Resources/InterfaceIcons.lua
Labels: enhancement

#979 Patch/status panel choices
  totalRP3/Locales/deDE.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/esES.lua
  totalRP3/Locales/frFR.lua
  totalRP3/Locales/ptBR.lua
  totalRP3/Locales/ruRU.lua
  totalRP3/Locales/zhCN.lua
  totalRP3/Locales/zhTW.lua
  totalRP3/Modules/Dashboard/StatusPanel.lua
Labels: enhancement

#976 New toolbar button borders + ElvUI skinning
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/TargetFrame/TargetFrame.lua
  totalRP3/Modules/TargetFrame/TargetFrame.xml
  totalRP3/Modules/Toolbar/Toolbar.lua
  totalRP3/Modules/Toolbar/Toolbar.xml
  totalRP3/Modules/TooltipSkins/ElvUI.lua
Labels: enhancement

#978 Make character theme tooltip consistent
  totalRP3/Locales/deDE.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/esES.lua
  totalRP3/Locales/frFR.lua
  totalRP3/Locales/itIT.lua
  totalRP3/Locales/ptBR.lua
  totalRP3/Locales/ruRU.lua
  totalRP3/Locales/zhCN.lua
  totalRP3/Locales/zhTW.lua
  totalRP3/Modules/Register/Characters/RegisterAbout.lua
Labels: enhancement

#980 Glance buttons adjustments
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Register/Characters/RegisterMisc.lua
  totalRP3/Modules/Register/Main/RegisterGlance.lua
Labels: bug, enhancement

#981 Various icon size adjustments
  totalRP3/Modules/Register/Characters/RegisterUIAbout.xml
  totalRP3/Modules/Register/Characters/RegisterUICharacteristics.xml
  totalRP3/Modules/Register/Characters/RegisterUIMisc.xml
Labels: enhancement

#986 Relations tooltip fixes
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Characters/RegisterRelations.lua
  totalRP3/Modules/Register/Main/RegisterList.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: enhancement

#984 Add yet more backgrounds
  totalRP3/Core/UITools.lua
Labels: enhancement

#985 Resolve Classic errors with disabled dropdowns
  totalRP3/UI/Menu/DropdownButton_Legacy.lua
Labels: bug

#987 Change values for proficiency on MSP
  totalRP3/Modules/Register/MSP/RegisterMSP.lua
Labels: LibMSP

#951 Add walk-up support and tweak indicator icons
  totalRP3/Core/Enums.lua
  totalRP3/Core/Player.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Dashboard/Dashboard.lua
  totalRP3/Modules/Dashboard/Dashboard.xml
  totalRP3/Modules/Dashboard/StatusPanel.lua
  totalRP3/Modules/Dashboard/StatusPanel.xml
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Characters/RegisterUICharacteristics.xml
  totalRP3/Modules/Register/Characters/RegisterUIMain.xml
  totalRP3/Modules/Register/MSP/RegisterMSP.lua
  totalRP3/Modules/Register/Main/RegisterList.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
  totalRP3/Resources/UI/ui-walkup.tga
Labels: enhancement

#989 Misc Info Icon button - Remove OnClick script
  totalRP3/Modules/Register/Characters/RegisterUICharacteristics.xml
Labels: bug

#988 Refactor menus/dropdowns and duplicate button
  totalRP3/Core/Popup.lua
  totalRP3/Core/Profiles.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Dashboard/Dashboard.lua
  totalRP3/Modules/Languages/Languages.lua
  totalRP3/Modules/Map/WorldMapButton.lua
  totalRP3/Modules/ModuleManagement.lua
  totalRP3/Modules/Register/Characters/RegisterAbout.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Characters/RegisterRelations.lua
  totalRP3/Modules/Register/Characters/RegisterUICharacteristics.xml
  totalRP3/Modules/Register/Companions/RegisterCompanionsPage.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
  totalRP3/Modules/Register/Main/RegisterGlance.lua
  totalRP3/Modules/Register/Main/RegisterList.lua
  totalRP3/Modules/TargetFrame/TargetFrame.lua
  totalRP3/Modules/Toolbar/Toolbar.lua
Labels: enhancement

#992 Fix profile errors while still receiving data
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Main/RegisterList.lua
Labels: bug

#993 Fix sorting down arrows on directory
  totalRP3/Modules/Register/Main/RegisterList.lua
Labels: bug

#994 Characterictics UI tweaks
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Characters/RegisterUICharacteristics.xml
  totalRP3/Modules/Register/Main/RegisterTemplates.xml
Labels: enhancement

#996 Add SetIconTextureTo* methods for bordered icons
  totalRP3/Modules/TargetFrame/TargetFrame.lua
  totalRP3/UI/IconTemplates.lua
Labels: enhancement

#997 Fix overlap of character name and walkup icons
  totalRP3/Modules/Register/Characters/RegisterUICharacteristics.xml
Labels: bug

#998 Add companion icon to sidebar list entries
  totalRP3/Modules/Register/Main/RegisterList.lua
Labels: bug, enhancement, unenhancement

#999 Increase minimum window size
  totalRP3/UI/Main.lua
  totalRP3/UI/Main.xml
Labels: enhancement

#1000 Sort directory sidebar list by order-of-opening
  totalRP3/Core/MainStructure.lua
  totalRP3/Modules/Register/Main/RegisterList.lua
Labels: enhancement

#991 Add resize cursor while resizing the main window
  totalRP3/Core/UITools.lua
  totalRP3/UI/Main.xml
Labels: enhancement

#1001 Only run most actions within our org
  .github/workflows/export-all-translations.yml
  .github/workflows/export-translations.yml
  .github/workflows/import-translations.yml
  .github/workflows/release.yml
  .github/workflows/release_beta.yml
Labels: bug, enhancement, third-party

#1007 Don't show minimum frame size as invalid
  totalRP3/Core/UITools.lua
Labels: bug

#1005 Added safety for missing companion name
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
Labels: bug

#1006 Convert profile managers to scrollbox list views
  .luacheckrc
  totalRP3/Core/Profiles.lua
  totalRP3/Modules/Importer/Importer.lua
  totalRP3/Modules/Importer/Importer.xml
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
  totalRP3/UI/ProfileManager/ProfileManager.xml
  totalRP3/UI/ProfileManager/ProfileManagerList.lua
  totalRP3/UI/ProfileManager/ProfileManagerList.xml
  totalRP3/UI/ProfileManager/ProfileManagerListElement.lua
  totalRP3/UI/ProfileManager/ProfileManagerListElement.xml
  totalRP3/UI/Profiles.xml
  totalRP3/UI/Widgets.lua
  totalRP3/UI/Widgets.xml
Labels: enhancement

#941 New tooltip description and rendering system
  .luacheckrc
  totalRP3/Core/Profiles.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
  totalRP3/UI/TabSystem.lua
  totalRP3/UI/Tooltip/Tooltip.lua
  totalRP3/UI/Tooltip/Tooltip.xml
  totalRP3/UI/Tooltip/TooltipScript.lua
  totalRP3/UI/Tooltip/TooltipScript.xml
  totalRP3/UI/Tooltip/TooltipTemplates.lua
  totalRP3/UI/Tooltip/TooltipUtil.lua
  totalRP3/UI/Widgets.lua
  totalRP3/UI/Widgets.xml
Labels: enhancement

#1008 Fix issues with enabling/disabling modules
  totalRP3/Modules/ModuleManagement.lua
Labels: bug

#1009 Don't register the button when target frame doesn't exist
  totalRP3/Modules/Register/Characters/RegisterRelations.lua
Labels: bug

#982 Consistency pass of settings pages
  totalRP3/Core/Configuration.lua
  totalRP3/Locales/deDE.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/esES.lua
  totalRP3/Locales/esMX.lua
  totalRP3/Locales/frFR.lua
  totalRP3/Locales/itIT.lua
  totalRP3/Locales/ptBR.lua
  totalRP3/Locales/ruRU.lua
  totalRP3/Locales/zhCN.lua
  totalRP3/Locales/zhTW.lua
  totalRP3/Modules/Map/WorldMapButton.lua
  totalRP3/Modules/Register/Characters/RegisterMain.lua
  totalRP3/Modules/Register/Main/RegisterGlance.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
  totalRP3/Modules/TargetFrame/TargetFrame.lua
  totalRP3/Modules/Toolbar/Toolbar.lua
Labels: enhancement

#1003 Convert preset additional info & traits to custom
  totalRP3/Core/ProfileUtil.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
Labels: enhancement

#1010 Fix height of non-additional info lines
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Characters/RegisterUICharacteristics.xml
Labels: bug

#1012 Make profile list less snappy
  .luacheckrc
  totalRP3/Core/Profiles.lua
Labels: bug

#1014 Trim spaces from race/class text
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: enhancement

#1013 Tweak chat links a bit
  totalRP3/Core/ProfilesChatLinksModule.lua
  totalRP3/Modules/ChatLinks/ChatLinks.lua
  totalRP3/Modules/ChatLinks/ChatLinks.xml
  totalRP3/Modules/Register/Main/RegisterPlayerChatLinksModule.lua
Labels: enhancement

#1015 Disable world cursor unit support by default
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: unenhancement

#1016 Tooltip Settings: Current --> Currently
  totalRP3/Locales/enUS.lua
Labels: consistency

#1017 Prefer unmodified unit names in certain contexts
  totalRP3/Core/Globals.lua
  totalRP3/Core/UITools.lua
  totalRP3/Core/Utils.lua
  totalRP3/Libs/Ellyb/Tools/Unit.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsMain.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: bug

#1018 Tooltips deserve global recogn-- colors
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: consistency

#1019 Twins are better than duplicate strings - Trust me
  totalRP3/Locales/enUS.lua
Labels: bug

#1020 Allow client version/info to be toggled
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: enhancement

#1022 RP styles text improvement
  totalRP3/Locales/enUS.lua
Labels: consistency

#1021 Mark empty abouts as read (combined flyway with inactive glances)
  totalRP3/Modules/Flyway/Flyway.lua
  totalRP3/Modules/Flyway/FlywayPatches.lua
  totalRP3/Modules/Register/Characters/RegisterAbout.lua
Labels: bug

#1023 Read summoned pet IDs from correct location
  totalRP3/Modules/Register/Companions/RegisterCompanionsMain.lua
Labels: bug

#1024 Scrollbox the register list page
  totalRP3/Modules/Register/Main/RegisterList.lua
  totalRP3/Modules/Register/Main/RegisterUIList.xml
Labels: unenhancement, consistency

#1028 Only allow disabling purge in debug builds
  totalRP3/Modules/Register/Characters/RegisterMain.lua
Labels: unenhancement

#1025 Add background browser for about pages
  totalRP3/Core/Core.xml
  totalRP3/Core/Popup.lua
  totalRP3/Core/UITools.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Register/Characters/RegisterAbout.lua
  totalRP3/Modules/Register/Characters/RegisterUIAbout.xml
  totalRP3/Modules/Register/Companions/RegisterCompanionsPage.lua
  totalRP3/Modules/Register/Companions/RegisterUICompanionsPage.xml
  totalRP3/UI/Tooltip/TooltipTemplates.lua
Labels: enhancement, help wanted, unenhancement

#1027 Tweak and remove comms pooling settings
  totalRP3/Core/AdvancedSettings.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/esES.lua
  totalRP3/Locales/esMX.lua
  totalRP3/Locales/frFR.lua
  totalRP3/Locales/ptBR.lua
  totalRP3/Locales/ruRU.lua
  totalRP3/Locales/zhCN.lua
  totalRP3/Modules/Register/Main/RegisterExchange.lua
Labels: enhancement

#1026 Use same anchors when scrollbar is and isn't present for register list
  totalRP3/Modules/Register/Main/RegisterList.lua
Labels: bug, unenhancement

#1030 Add the missing background browser files
  totalRP3/Modules/Register/Characters/RegisterUIAbout.xml
  totalRP3/UI/Browsers/BackgroundBrowser.lua
  totalRP3/UI/Browsers/BackgroundBrowser.xml
Labels: enhancement

#1031 Interface atlases support + Refresh frames icons
  totalRP3/Modules/Register/Characters/RegisterIgnore.lua
  totalRP3/Modules/Register/Characters/RegisterNotes.lua
  totalRP3/Modules/Register/Characters/ReportProfileButton.lua
  totalRP3/Modules/Register/Main/RegisterList.lua
  totalRP3/Modules/TargetFrame/TargetFrame.lua
  totalRP3/Modules/Toolbar/Toolbar.lua
  totalRP3/Resources/InterfaceAtlases.lua
  totalRP3/Resources/InterfaceIcons.lua
  totalRP3/Resources/Resources.xml
Labels: enhancement

#1033 Fix Template 2 edit background
  totalRP3/Modules/Register/Characters/RegisterAbout.lua
Labels: bug

#1034 Fix icon's copy name
  totalRP3/Core/Popup.lua
  totalRP3/Modules/Register/Characters/RegisterAbout.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsPage.lua
  totalRP3/Modules/Register/Main/RegisterGlance.lua
Labels: bug

#1035 Change cursor to glance icon on drag
  totalRP3/Modules/Register/Main/RegisterGlance.lua
Labels: bug

#1036 Add option to display full relations in tooltips
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: enhancement

#1037 Reset isFading on showing the toast
  totalRP3/Core/UITools.lua
Labels: bug

#1038 Popups on escape now just close themselves
  totalRP3/Core/Popup.lua
  totalRP3/Modules/Register/Characters/RegisterRelations.lua
  totalRP3/Modules/Register/Main/RegisterGlance.lua
Labels: enhancement

#1039 Remove duplicated loc keys + settings dropdown consistency
  totalRP3/Locales/deDE.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/esES.lua
  totalRP3/Locales/esMX.lua
  totalRP3/Locales/frFR.lua
  totalRP3/Locales/itIT.lua
  totalRP3/Locales/ptBR.lua
  totalRP3/Locales/ruRU.lua
  totalRP3/Locales/zhCN.lua
  totalRP3/Locales/zhTW.lua
  totalRP3/Modules/Automation/Automation_Actions.lua
  totalRP3/Modules/Dashboard/StatusPanel.lua
  totalRP3/Modules/NamePlates/NamePlates_Settings.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Characters/RegisterMain.lua
  totalRP3/Modules/Register/Characters/RegisterMisc.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsPage.lua
  totalRP3/Modules/Register/Filter/RegisterMatureFilter.lua
  totalRP3/Modules/Register/Main/RegisterList.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
  totalRP3/Modules/TargetFrame/TargetFrame.lua
  totalRP3/Modules/Toolbar/Toolbar.lua
Labels: consistency

#1040 Add nil check on character ID in GetRoleplayExperience
  totalRP3/Core/Player.lua
Labels: bug

#1041 No string left ignored
  totalRP3/Modules/Register/Main/RegisterList.lua
Labels: bug

#990 Added unread icon on About tab
  totalRP3/Core/UITools.lua
  totalRP3/Modules/Register/Characters/RegisterMain.lua
  totalRP3/UI/TabSystem.lua
  totalRP3/UI/TabSystem.xml
Labels: enhancement

#1043 Adjust tooltip anchors on toolbar and target frame based on screen position
  totalRP3/Core/UITools.lua
  totalRP3/Modules/Register/Main/RegisterGlance.lua
  totalRP3/Modules/TargetFrame/TargetFrame.lua
  totalRP3/Modules/Toolbar/Toolbar.lua
Labels: enhancement

#1044 Rework notification icons
  totalRP3/Modules/Dashboard/StatusPanel.lua
  totalRP3/Modules/Register/Characters/RegisterMain.lua
  totalRP3/Modules/Register/Characters/RegisterNotes.lua
  totalRP3/Modules/Register/Characters/RegisterUICharacteristics.xml
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
  totalRP3/Modules/Register/Main/RegisterList.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
  totalRP3/Modules/TargetFrame/TargetFrame.xml
  totalRP3/Resources/UI/ui-icon-edit.tga
  totalRP3/Resources/UI/ui-icon-note.tga
  totalRP3/Resources/UI/ui-icon-unread-overlay.tga
  totalRP3/Resources/UI/ui-icon-unread.tga
  totalRP3/Resources/UI/ui-icon-walkup.tga
  totalRP3/Resources/UI/ui-walkup.tga
Labels: enhancement

#1045 Add basic pushed state for icon buttons
  totalRP3/Modules/Register/Characters/RegisterUIMisc.xml
  totalRP3/Modules/Register/Characters/RegisterUIRelations.xml
  totalRP3/Modules/TargetFrame/TargetFrame.xml
  totalRP3/Modules/Toolbar/Toolbar.xml
  totalRP3/Resources/UI/ui-frame-slice-sm-pushed.tga
  totalRP3/UI/IconTemplates.xml
Labels: unenhancement

#1046 Swap template for action button in Characteristics tab of other players
  totalRP3/Modules/Register/Characters/RegisterUICharacteristics.xml
Labels: enhancement

#1047 Add an absolute unit of an edit button
  totalRP3/Modules/Modules.xml
  totalRP3/Modules/Register/Characters/RegisterAbout.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Characters/RegisterUIAbout.xml
  totalRP3/Modules/Register/Characters/RegisterUICharacteristics.xml
  totalRP3/Modules/Register/Companions/RegisterCompanionsPage.lua
  totalRP3/Modules/Register/Companions/RegisterUICompanionsPage.xml
  totalRP3/Resources/UI/Templates.xml
  totalRP3/Resources/UI/ui-red-buttons.tga
Labels: enhancement

#1048 Cancelling locale change should not change locale
  totalRP3/Core/AdvancedSettings.lua
Labels: bug

#1049 Allow changing WU field state from default profile
  totalRP3/Core/Player.lua
Labels: bug

#1050 All dropdowns get consistent + Some delete relation stuff
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Dashboard/StatusPanel.lua
  totalRP3/Modules/Register/Characters/RegisterMisc.lua
  totalRP3/Modules/Register/Characters/RegisterRelations.lua
Labels: consistency

#1052 Companion at a glance info tooltip consistency
  totalRP3/Modules/Register/Companions/RegisterCompanionsPage.lua
Labels: consistency

#1053 Increase additional info height by 2px
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
Labels: enhancement

#1059 Fix Classic compatibility
  totalRP3/Modules/Dashboard/Dashboard.lua
  totalRP3/Resources/InterfaceIcons.lua
  totalRP3/UI/Tooltip/Tooltip.lua
  totalRP3/UI/Widgets.lua
  totalRP3/UI/Widgets.xml
Labels: bug

#1054 Tooltip on about unread tab
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Register/Characters/RegisterMain.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
  totalRP3/Modules/Register/Main/RegisterList.lua
  totalRP3/UI/TabSystem.lua
Labels: enhancement, consistency

#1055 Only test Y coordinate axis when dragging MI/PS
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
Labels: bug

#1056 Toggle IC/OOC status on toolbutton click
  totalRP3/Modules/Dashboard/Dashboard.lua
Labels: consistency

#1057 Debounce CU/CO field edits
  totalRP3/Modules/Dashboard/Currently.lua
  totalRP3/Modules/Register/Characters/RegisterMisc.lua
Labels: enhancement

#1058 Bump TOC versions
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .github/workflows/release_beta.yml
  Makefile
  totalRP3/totalRP3.toc
  totalRP3_Data/totalRP3_Data.toc
Labels: enhancement

#1060 Use fixed height for notification lines in all TTs
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: bug, consistency

#1061 Fix action button position for companions
  totalRP3/Modules/Register/Companions/RegisterUICompanionsPage.xml
Labels: bug

#1062 Reduce crop lengths on NA and FT by 50 characters
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: unenhancement

#1064 Fix map scan context menu parent
  totalRP3/Modules/Map/WorldMapButton.lua
Labels: bug

#1063 Colon-delimit mount info in tooltip
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: consistency

#1066 Remove internal logging buffer
  totalRP3/Core/Logging.lua
Labels: unenhancement

#1065 Fix duplicate or missing click sounds
  totalRP3/Modules/Automation/Automation_Settings.lua
  totalRP3/Modules/Map/Map.xml
  totalRP3/Modules/Register/Characters/RegisterAbout.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/UI/Menu/Menu.lua
  totalRP3/UI/Widgets.xml
Labels: bug

#1068 Avoid GameTooltip:IsOwned API
  totalRP3/Modules/Launcher/Launcher_Settings.lua
  totalRP3/UI/Menu/MenuUtil.lua
  totalRP3/UI/Tooltip/TooltipScript.lua
  totalRP3/UI/Tooltip/TooltipUtil.lua
Labels: bug

#1069 Add click sounds to many popup close buttons
  totalRP3/Modules/Register/Characters/RegisterRelations.lua
  totalRP3/Modules/Register/Filter/RegisterMatureFilter.xml
  totalRP3/UI/Browsers/Colors.xml
  totalRP3/UI/Browsers/Images.xml
  totalRP3/UI/Browsers/Musics.xml
Labels: bug

#1070 Add open/close sounds to NPCTalk and Currently
  totalRP3/Modules/Dashboard/Currently.lua
  totalRP3/Modules/Dashboard/NPCTalk.lua
Labels: enhancement

#1071 Fix double click sounds on Links button
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
Labels: bug

#1072 Fix error when resizing the glance editor
  totalRP3/Core/UITools.lua
Labels: bug

#1076 Truncate race/class texts to 30 chars in TTs
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: unenhancement

#1077 Don't overwrite CU/CO with other peoples data
  totalRP3/Modules/Register/Characters/RegisterMisc.lua
Labels: bug

#1074 Fix guild membership style localization
  totalRP3/Locales/enUS.lua
Labels: consistency

#1073 Actually allow relation icons to be copied/pasted
  totalRP3/Modules/Register/Characters/RegisterRelations.lua
Labels: enhancement

#1078 Shift -> Shift-Click in click handlers
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Characters/RegisterRelations.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsPage.lua
Labels: enhancement, consistency

#1075 Add truncation tooltips to most fields
  totalRP3/Modules/Register/Characters/RegisterUICharacteristics.xml
  totalRP3/Modules/Register/Companions/RegisterUICompanionsPage.xml
  totalRP3/UI/TabSystem.lua
  totalRP3/UI/Tooltip/TooltipScript.lua
  totalRP3/UI/Tooltip/TooltipScript.xml
  totalRP3/UI/Tooltip/TooltipTemplates.lua
  totalRP3/UI/Widgets.lua
Labels: enhancement

#917 Clean up deprecated dropdown aliases
  totalRP3/Deprecated.xml
Labels: unenhancement

#1081 Importing is not exporting, silly menu
  totalRP3/Core/Profiles.lua
Labels: bug

#1082 Fix copy icon name on profile icons (IC)
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
Labels: bug

#1083 Add UI asset sources
  .pkgmeta
  totalRP3/Resources/UI/ui-category-button.tga
  totalRP3/Resources/UI/ui-icon-edit.tga
  totalRP3/Resources/UI/ui-icon-note.tga
  totalRP3/Resources/UI/ui-icon-unread-overlay.tga
  totalRP3/Resources/UI/ui-icon-unread.tga
  totalRP3/Resources/UI/ui-icon-walkup.tga
  totalRP3/Resources/UI/ui-sheet.afdesign
Labels: unenhancement

#1084 Fix tutorial on profiles list
  totalRP3/Core/Profiles.lua
Labels: bug

#1085 Remove old changelogs
  totalRP3/Locales/enUS.lua
Labels: unenhancement

#1079 Centralize soundkit definitions and add more sounds
  totalRP3/Core/MainStructure.lua
  totalRP3/Core/Popup.lua
  totalRP3/Core/Profiles.lua
  totalRP3/Core/UITools.lua
  totalRP3/Libs/Ellyb/UI/Popups.lua
  totalRP3/Modules/Automation/Automation_Settings.lua
  totalRP3/Modules/Dashboard/Currently.lua
  totalRP3/Modules/Dashboard/Dashboard.lua
  totalRP3/Modules/Dashboard/NPCTalk.lua
  totalRP3/Modules/Importer/Importer.lua
  totalRP3/Modules/Register/Characters/RegisterAbout.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Characters/RegisterRelations.lua
  totalRP3/Modules/Register/Characters/RegisterUIMisc.xml
  totalRP3/Modules/Register/Companions/RegisterCompanionsPage.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
  totalRP3/Modules/Register/Filter/RegisterMatureFilter.lua
  totalRP3/Modules/Register/Filter/RegisterMatureFilter.xml
  totalRP3/Modules/Register/Main/RegisterGlance.lua
  totalRP3/Modules/Toolbar/Toolbar.lua
  totalRP3/Resources/InterfaceSounds.lua
  totalRP3/Resources/Resources.xml
  totalRP3/UI/Browsers/BackgroundBrowser.lua
  totalRP3/UI/Browsers/Colors.xml
  totalRP3/UI/Browsers/IconBrowser.lua
  totalRP3/UI/Browsers/Images.xml
  totalRP3/UI/Browsers/Musics.xml
  totalRP3/UI/Browsers/PetBrowser.lua
  totalRP3/UI/Main.xml
  totalRP3/UI/Menu/DropdownButton_Legacy.lua
  totalRP3/UI/Menu/Menu.lua
  totalRP3/UI/ProfileManager/ProfileManagerListElement.xml
  totalRP3/UI/Widgets.xml
Labels: enhancement, consistency

#1088 Remove special handling of empty custom class on MSP
  totalRP3/Modules/Register/MSP/RegisterMSP.lua
Labels: bug

#1089 Fix tutorial overlay for companion profile list
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
Labels: bug

#1091 Murder the FieldSetFrame template
  totalRP3/Deprecated.lua
  totalRP3/Deprecated.xml
Labels: unenhancement

#1087 Convert music browser to use scrollbox list view
  .luacheckrc
  totalRP3/Core/Core.xml
  totalRP3/Core/Popup.lua
  totalRP3/Resources/MusicList.lua
  totalRP3/Resources/Resources.xml
  totalRP3/UI/Browsers/MusicBrowser.lua
  totalRP3/UI/Browsers/MusicBrowser.xml
  totalRP3/UI/Browsers/Musics.xml
  totalRP3/UI/Tooltip/Tooltip.lua
  totalRP3/UI/Tooltip/TooltipTemplates.lua
Labels: enhancement

#1092 Strip consecutive spaces from FT fields
  totalRP3/Modules/NamePlates/NamePlates_Shared.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsPage.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: unenhancement

#961 3.0 changelog
  CHANGELOG.md
  totalRP3/Modules/Dashboard/WhatsNewTabView.lua
Labels: enhancement

#1090 Add centralized search string cache
  totalRP3/Core/StringUtil.lua
  totalRP3/UI/Browsers/BackgroundBrowser.lua
  totalRP3/UI/Browsers/IconBrowser.lua
  totalRP3/UI/Browsers/MusicBrowser.lua
Labels: consistency

#1093 Default CU if unset for Currently frame
  totalRP3/Modules/Dashboard/Currently.lua
Labels: bug

#1101 Update credits
  totalRP3/Modules/Dashboard/AboutTabView.lua
Labels: unenhancement

#1097 Only check world cursor config if TT module is on
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: bug

#1098 Scrollable switch profile dropdowns if list too big
  totalRP3/Modules/Dashboard/Dashboard.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
Labels: enhancement

#1100 Remove glance click handlers
  totalRP3/Modules/Register/Characters/RegisterMisc.lua
  totalRP3/Modules/Register/Main/RegisterGlance.lua
Labels: unenhancement

#1102 Relations icon pasting fix redux
  totalRP3/Modules/Register/Characters/RegisterRelations.lua
Labels: bug
