Repository Total-RP/Total-RP-3, pull requests merged in 2024-12, with the labels that each got.

#1151 Strictly validate interface icons on load
  totalRP3/Resources/InterfaceIcons.lua
Labels: unenhancement

#1154 Add warning when chat is disabled
  .luacheckrc
  totalRP3/Locales/enUS.lua
  totalRP3/totalRP3.lua
Labels: enhancement

#1155 Improve toolbar object addon compatibility
  totalRP3/Modules/Dashboard/Currently.lua
  totalRP3/Modules/Dashboard/Dashboard.lua
  totalRP3/Modules/Languages/Languages.lua
  totalRP3/Modules/Toolbar/Toolbar.lua
Labels: enhancement

#1156 Use the correct function to check for icons
  totalRP3/Resources/InterfaceIcons.lua
Labels: bug
