Repository Total-RP/Total-RP-3, pull requests merged in 2024-08, with the labels that each got.

#1105 Issue profile requests on target bar interactions
  totalRP3/Modules/Languages/Languages.lua
  totalRP3/Modules/Register/Characters/RegisterRelations.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsProfiles.lua
  totalRP3/Modules/Register/Main/RegisterList.lua
Labels: consistency

#1107 Aggressively trim notes prior to saving
  totalRP3/Modules/Register/Characters/RegisterNotes.lua
Labels: unenhancement

#1109 Update crop text tooltip
  totalRP3/Locales/deDE.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/esES.lua
  totalRP3/Locales/frFR.lua
  totalRP3/Locales/ptBR.lua
  totalRP3/Locales/ruRU.lua
  totalRP3/Locales/zhCN.lua
  totalRP3/Locales/zhTW.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
Labels: enhancement

#1112 Defer combat status toggle by one frame
  totalRP3/Modules/NamePlates/NamePlates_Core.lua
Labels: bug

#1108 Toolbar Modernization (and also IC/OOC icons)
  totalRP3/Core/Configuration.lua
  totalRP3/Modules/Dashboard/Dashboard.lua
  totalRP3/Modules/Languages/Languages.lua
  totalRP3/Modules/TargetFrame/TargetFrame.lua
  totalRP3/Modules/Toolbar/Toolbar.lua
  totalRP3/Modules/Toolbar/Toolbar.xml
  totalRP3/Modules/Toolbar/ToolbarButton.lua
  totalRP3/Modules/Toolbar/ToolbarButton.xml
  totalRP3/Modules/Toolbar/ToolbarConstants.lua
  totalRP3/Modules/Toolbar/ToolbarFrame.lua
  totalRP3/Modules/Toolbar/ToolbarFrame.xml
  totalRP3/Modules/Toolbar/ToolbarUtil.lua
  totalRP3/Modules/TooltipSkins/ElvUI.lua
  totalRP3/Resources/InterfaceIcons.lua
  totalRP3/UI/Tooltip/Tooltip.lua
  totalRP3/UI/Tooltip/TooltipTemplates.lua
Labels: enhancement

#1114 Remove transmission support for PS VAs
  .luacheckrc
  totalRP3/Core/Globals.lua
  totalRP3/Modules/Flyway/Flyway.lua
  totalRP3/Modules/Flyway/FlywayPatches.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/MSP/Fields.lua
Labels: unenhancement

#1116 Don't propagate buttons on map pins in combat
  .luacheckrc
  totalRP3/Modules/Map/MapPoiMixins.lua
Labels: bug

#1115 Fix constant related error in pet browser
  totalRP3/UI/Browsers/PetBrowser.lua
Labels: bug

#1113 Extend and improve color contrasting
  .luacheckrc
  totalRP3/Core/Color.lua
  totalRP3/Core/ColorData.lua
  totalRP3/Core/Configuration.lua
  totalRP3/Core/Core.xml
  totalRP3/Core/Player.lua
  totalRP3/Core/Popup.lua
  totalRP3/Locales/deDE.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/esES.lua
  totalRP3/Locales/esMX.lua
  totalRP3/Locales/frFR.lua
  totalRP3/Locales/itIT.lua
  totalRP3/Locales/koKR.lua
  totalRP3/Locales/ptBR.lua
  totalRP3/Locales/ruRU.lua
  totalRP3/Locales/zhCN.lua
  totalRP3/Locales/zhTW.lua
  totalRP3/Modules/ChatFrame/ChatFrame.lua
  totalRP3/Modules/NamePlates/NamePlates_Core.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Characters/RegisterUICharacteristics.xml
  totalRP3/Modules/Register/Companions/RegisterCompanionsPage.lua
  totalRP3/Modules/Register/Companions/RegisterUICompanionsPage.xml
  totalRP3/Modules/Register/Main/RegisterTemplates.lua
  totalRP3/Modules/Register/Main/RegisterTooltip.lua
  totalRP3/UI/Browsers/ColorBrowser.lua
  totalRP3/UI/Browsers/ColorBrowser.xml
  totalRP3/UI/Browsers/Colors.xml
  totalRP3/UI/ColorSwatch.lua
  totalRP3/UI/ColorSwatch.xml
  totalRP3/UI/Configuration.xml
  totalRP3/UI/Menu/MenuTemplates.lua
  totalRP3/UI/TextUtil.lua
  totalRP3/UI/Tooltip/TooltipScript.lua
  totalRP3/UI/Tooltip/TooltipScript.xml
  totalRP3/UI/Widgets.lua
  totalRP3/UI/Widgets.xml
Labels: enhancement

#1117 Small tweaks to CO/CU debouncing on Misc page
  totalRP3/Modules/Register/Characters/RegisterMisc.lua
Labels: bug

#1119 Fix pin button passthrough for 11.0.2
  totalRP3/Modules/Register/Characters/PlayerMapScan/PlayerMapPin.lua
Labels: bug

#1120 Color swatch tweaks
  totalRP3/Modules/Register/Characters/RegisterUICharacteristics.xml
  totalRP3/Modules/Register/Main/RegisterTemplates.lua
  totalRP3/UI/ColorSwatch.xml
Labels: consistency

#1121 Add monochromatic contrast level
  totalRP3/Core/Color.lua
  totalRP3/Core/Configuration.lua
  totalRP3/Locales/enUS.lua
Labels: enhancement

#1124 Improve error display logic for modules
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/ChatFrame/ElvUI.lua
  totalRP3/Modules/ChatFrame/WIM.lua
  totalRP3/Modules/ModuleManagement.lua
  totalRP3/Modules/NamePlates/NamePlates_Blizzard.lua
  totalRP3/Modules/TooltipSkins/ElvUI.lua
  totalRP3/Modules/TooltipSkins/TinyTooltip.lua
  totalRP3/Modules/TooltipSkins/Tiptac.lua
Labels: enhancement

#1125 Fix hiding of icons and titles on Kui nameplates
  totalRP3/Modules/NamePlates/NamePlates_Kui.lua
Labels: bug

#1127 Rename menu settings
  totalRP3/Locales/deDE.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/frFR.lua
Labels: enhancement

#1128 Focus hex input field on color browser open
  totalRP3/UI/Browsers/ColorBrowser.lua
Labels: enhancement
