Repository Total-RP/Total-RP-3, pull requests merged in 2025-03, with the labels that each got.

#1172 Add BSky link support for Dashboard
  AUTHORS.md
  README.md
  totalRP3/Core/Utils.lua
  totalRP3/Modules/Dashboard/DashboardCredits.lua
  totalRP3/UI/HTML/LinkUtil.lua
Labels: enhancement

#1173 Color options (right-click copy color, color name, paste color)
  totalRP3/Core/Popup.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Modules/Register/Characters/RegisterAbout.lua
  totalRP3/Modules/Register/Characters/RegisterCharacteristics.lua
  totalRP3/Modules/Register/Characters/RegisterRelations.lua
  totalRP3/Modules/Register/Companions/RegisterCompanionsPage.lua
  totalRP3/Modules/Register/Main/RegisterGlance.lua
  totalRP3/Modules/Register/Main/RegisterTemplates.lua
  totalRP3/UI/Widgets.lua
  totalRP3/UI/Widgets.xml
Labels: enhancement

#1175 The good stuff
  totalRP3/Core/Configuration.lua
  totalRP3/UI/Main.xml
Labels: enhancement

#1177 Fix relative key issue in PetBrowser
  totalRP3/UI/Browsers/PetBrowser.xml
Labels: bug

#1178 Fix Prat realm removal setting
  totalRP3/Modules/ChatFrame/Prat.lua
Labels: bug

#1184 Titan is not a fun language
  totalRP3/Modules/Languages/Language.lua
Labels: consistency

#1183 Farewell, my dear TRP3_DEBUG_CODE_FRAME
  totalRP3/UI/Main.xml
Labels: enhancement

#1181 Fix "Open profile" not showing on community menus
  totalRP3/Modules/UnitPopups/UnitPopups.lua
Labels: bug

#1185 Remove WagoAnalytics integration
  .luacheckrc
  totalRP3/Locales/deDE.lua
  totalRP3/Locales/enUS.lua
  totalRP3/Locales/esES.lua
  totalRP3/Locales/frFR.lua
  totalRP3/Locales/ruRU.lua
  totalRP3/Locales/zhCN.lua
  totalRP3/Locales/zhTW.lua
  totalRP3/Modules/Analytics/Analytics.lua
  totalRP3/Modules/Analytics/Analytics.xml
  totalRP3/Modules/Analytics/Analytics_Data.lua
  totalRP3/Modules/Modules.xml
  totalRP3/totalRP3.toc
Labels: unenhancement
