Repository Total-RP/Total-RP-3, pull requests merged in 2025-02, with the labels that each got.

#1153 Remove old dropdown compatibility code
  .github/scripts/ui.xsd
  totalRP3/Modules/Automation/Automation_Settings.lua
  totalRP3/Modules/Dashboard/StatusPanel.lua
  totalRP3/UI/Menu/DropdownButton.lua
  totalRP3/UI/Menu/DropdownButton.xml
  totalRP3/UI/Menu/DropdownButton_Legacy.lua
  totalRP3/UI/Menu/DropdownButton_Shared.lua
  totalRP3/UI/Menu/Menu.lua
  totalRP3/UI/Menu/Menu.xml
  totalRP3/UI/Menu/MenuConstants.lua
  totalRP3/UI/Menu/MenuTemplates.lua
  totalRP3/UI/Menu/MenuUtil.lua
Labels: unenhancement

#1160 Add Group and Category TOC directives
  totalRP3/totalRP3.toc
  totalRP3_Data/totalRP3_Data.toc
Labels: enhancement

#1165 Fix error on opening walkup/proficiency/automation action dropdowns
  totalRP3/Modules/Automation/Automation_Settings.lua
  totalRP3/Modules/Dashboard/StatusPanel.lua
Labels: bug
